Allow toolbox containers to be created with a custom hostname
containers/toolbox pull request #1134
Opened 2022-10-13 11:32 UTC by nievesmontero

Based on the following pull request https://github.com/containers/toolbox/pull/1007

2022-10-14 00:50 UTC, debarshiray commented
> Based on the following pull request https://github.com/containers/toolbox/pull/1007

What's the difference from https://github.com/containers/toolbox/pull/1007 ?  Is this a rebase against `main`?

2022-10-14 00:52 UTC, debarshiray requested changes
The tests are failing:
```
not ok 25 create: Create a container with a custom hostname ('test.host-name.local') in 530ms
# (from function `assert_success' in file test/system/libs/bats-assert/src/assert.bash, line 114,
#  in test file test/system/101-create.bats, line 102)
#   `assert_success' failed
#
# -- command failed --
# status : 1
# output : Error: invalid hostname
# --
#
```

2022-10-14 01:45 UTC, debarshiray commented
Also, there are several issues and pull requests discussing various approaches to improve the host name.  For example, did you see https://github.com/containers/toolbox/pull/1086 that seems to implement https://github.com/containers/toolbox/issues/969 ?

I am curious why you picked https://github.com/containers/toolbox/pull/1007

I also remember that @allanday had some ideas about the host name, but I can't find a reference right now.

2022-10-14 01:47 UTC, debarshiray commented on src/cmd/create.go
> +	var hostnameRegexp = regexp.MustCompile(`^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\-]*[a-zA-Z0-9])\\.)*([A-Za-z0-9]|[A-Za-z0-9][a-zA-Z0-9\\-]*[a-zA-Z0-9])$`)
Do we really need to have this regular expression directly in the code?  Can't we use some Go package for it?

2022-10-19 12:51 UTC, nievesmontero commented
> > Based on the following pull request #1007
> 
> What's the difference from #1007 ? Is this a rebase against `main`?

Exactly, this new pull request is #1007 rebased against main. As #1007 was a bit old, there were conflicts I had to solve in order to be able to rebase it.

2022-10-19 12:51 UTC, nievesmontero commented
> Also, there are several issues and pull requests discussing various approaches to improve the host name. For example, did you see #1086 that seems to implement #969 ?
> 
> I am curious why you picked #1007
> 
> I also remember that @allanday had some ideas about the host name, but I can't find a reference right now.

This pull request was picked randomly, trying to solve older pull requests.

2022-10-26 21:32 UTC, akdev1l commented
@nievesmontero I would be partial towards picking the newest PR to merge instead of the oldest one

disclaimer: I'm the guy behind #1086 - totally willing to get this merged if you need some help

2022-10-27 11:48 UTC, nievesmontero commented
@akdev1l thank you for pointing this out. I have tried rebasing https://github.com/containers/toolbox/pull/1086 and it seems to work correctly. I will reach you if I need any help, thanks.

2022-11-17 18:39 UTC, debarshiray commented
> > > Based on the following pull request #1007
> > 
> > 
> > What's the difference from #1007 ? Is this a rebase against `main`?
> 
> Exactly, this new pull request is #1007 rebased against main. As #1007
> was a bit old, there were conflicts I had to solve in order to be able to
> rebase it.

I see.

Among other things, the tests are failing for this pull request, while they were passing for https://github.com/containers/toolbox/pull/1007

2022-11-17 18:43 UTC, debarshiray commented
> > Also, there are several issues and pull requests discussing various approaches to improve the host name. For example, did you see #1086 that seems to implement #969 ?
> > I am curious why you picked #1007
> > I also remember that @allanday had some ideas about the host name, but I can't find a reference right now.
> 
> This pull request was picked randomly, trying to solve older pull requests.

I see.  This can't be solved *randomly*.  :)

We have two broad issues.  One is about improving the default hostname for the containers (see https://github.com/containers/toolbox/issues/969), and the other is about making it easier to visually distinguish between containers (see https://github.com/containers/toolbox/issues/98).

I suggest going through those two issues, and all the other issues and pull requests linked from them to get a good idea of the current situation.  That will give you a good idea of what needs to be done.

2022-11-17 18:44 UTC, debarshiray commented
I am going to have to close this pull request because the comments from https://github.com/containers/toolbox/pull/1007 apply to this one too.

2022-11-17 18:44 UTC, closed without merging

2023-02-07 06:19 UTC, buck-ross commented
As the author of #1007, I agree with the decision to close both that PR and this one. #1086 seems to be a much simpler solution which addresses my initial issue without over-complicating things. Not to mention that the passage of time appears to have made integrating my original changes significantly more difficult.