Add dynamic linker option for riscv64
containers/toolbox pull request #1159
Opened 2022-11-16 06:19 UTC by Avimitin

This commit add dynamic linker for riscv 64 architecture. Tested in Arch Linux rv64gc qemu user image.

###  Addtional notes:

The old go module `golang.org/x/sys` doesn't contains implementation for RISC-V. We need to replace the module with v0.2.0.

```bash
go mod edit -replace golang.org/x/sys=golang.org/x/sys@v0.2.0
go mod download golang.org/x/sys
```

I don't know if this upgrade will affect the program, so changes are not included in this PR.

2022-11-17 21:48 UTC, debarshiray requested changes
Thanks for working on this, @Avimitin !  The patch looks mostly good.

Could you please prefix your commit message with a `build: ` tag and put a link at the bottom to this pull request, like we do in the other commits?

Out of curiosity, are you using Toolbx on riscv64 or generally interested in the architecture in some way?

2022-11-17 21:52 UTC, debarshiray commented
> The old go module `golang.org/x/sys` doesn't contains
> implementation for RISC-V. We need to replace the module
> with v0.2.0.

Are you sure about this one?  Currently, our `go.mod` has:
```
golang.org/x/sys v0.0.0-20211216021012-1d35b9e2eb4e
```

That's [this](https://github.com/golang/sys/commit/1d35b9e2eb4edf581781c7f3e2a36fac701f0a24) commit.  Support for linux/riscv64 was added in [this](https://github.com/golang/sys/commit/8cf3aee429924738c56c34bb819c4ea8273fc434) commit, which looks older.  Or am I missing something?

2022-11-18 04:10 UTC, Avimitin commented
Oh I have to force push, sry

2022-11-18 04:12 UTC, Avimitin commented
> Out of curiosity, are you using Toolbx on riscv64 or generally interested in the architecture in some way?

I am now working for an unofficial project that porting the Arch Linux packages to RISC-V. And this package fails to build so I try to fixed it.

2022-11-18 04:17 UTC, Avimitin commented
> > The old go module `golang.org/x/sys` doesn't contains
> > implementation for RISC-V. We need to replace the module
> > with v0.2.0.
> 
> Are you sure about this one? Currently, our `go.mod` has:
> 
> ```
> golang.org/x/sys v0.0.0-20211216021012-1d35b9e2eb4e
> ```
> 
> That's [this](https://github.com/golang/sys/commit/1d35b9e2eb4edf581781c7f3e2a36fac701f0a24) commit. Support for linux/riscv64 was added in [this](https://github.com/golang/sys/commit/8cf3aee429924738c56c34bb819c4ea8273fc434) commit, which looks older. Or am I missing something?

My description is not accurate enough. The current `sys` package did has rv64 implementation but is not complete. So the Go compiler complaining `missing function body` during compilation process. I don't know which function is missing and I will try to figure it out.

2022-11-18 06:39 UTC, debarshiray commented
> > Out of curiosity, are you using Toolbx on riscv64 or generally interested
> > in the architecture in some way?
> 
> I am now working for an unofficial project that porting the Arch Linux
> packages to RISC-V. And this package failed to build so I tried to fix it.

That sounds like an interesting project.  :)

2022-11-18 06:55 UTC, debarshiray commented
> > Are you sure about this one? Currently, our `go.mod` has:
> > ```
> > golang.org/x/sys v0.0.0-20211216021012-1d35b9e2eb4e
> > ```
> >   
> > That's [this](https://github.com/golang/sys/commit/1d35b9e2eb4edf581781c7f3e2a36fac701f0a24) commit. Support for linux/riscv64 was added in [this](https://github.com/golang/sys/commit/8cf3aee429924738c56c34bb819c4ea8273fc434) commit, which looks older. Or am I missing something?
> 
> My description is not accurate enough. The current `sys` package did has rv64 implementation but is not complete. So the Go compiler complaining `missing function body` during compilation process. I don't know which function is missing and I will try to figure it out.

I see.  Could it be because of [this](https://github.com/golang/sys/commit/4c3a928424d249a1013e789cf5e458d480bcba16) commit.  Maybe we should try updating the dependency to [this](https://github.com/golang/sys/commit/2f3576d2c59b42b60d62d49998f5ba42bf45c5f5) commit?

I think we also [need](https://tip.golang.org/doc/go1.14#riscv) to bump our required Go version to 1.14 in `src/go.mod` from the current 1.13.

2022-11-18 09:28 UTC, Avimitin commented
> I see. Could it be because of [this](https://github.com/golang/sys/commit/4c3a928424d249a1013e789cf5e458d480bcba16) commit. Maybe we should try updating the dependency to [this](https://github.com/golang/sys/commit/2f3576d2c59b42b60d62d49998f5ba42bf45c5f5) commit?
 
 Probably not this one, I am still try digging. Here is the full compile error output:
 
 ```text
# golang.org/x/sys/unix
/build/go/pkg/mod/golang.org/x/sys@v0.0.0-20190422165155-953cdadca894/unix/syscall_linux_gc.go:10:6: missing function body
/build/go/pkg/mod/golang.org/x/sys@v0.0.0-20190422165155-953cdadca894/unix/syscall_linux_gc.go:14:6: missing function body
/build/go/pkg/mod/golang.org/x/sys@v0.0.0-20190422165155-953cdadca894/unix/syscall_unix_gc.go:12:6: missing function body
/build/go/pkg/mod/golang.org/x/sys@v0.0.0-20190422165155-953cdadca894/unix/syscall_unix_gc.go:13:6: missing function body
/build/go/pkg/mod/golang.org/x/sys@v0.0.0-20190422165155-953cdadca894/unix/syscall_unix_gc.go:14:6: missing function body
/build/go/pkg/mod/golang.org/x/sys@v0.0.0-20190422165155-953cdadca894/unix/syscall_unix_gc.go:15:6: missing function body
```

2022-11-18 09:33 UTC, Avimitin commented
Oh my fault, I don't explain the whole build environment. The current version of the toolbox package in Arch Linux is currently 0.0.99.33. I will try if the `v0.0.0-20211216021012-1d35b9e2eb4e` version of the `sys` package specified in master branch works.

2022-11-18 09:47 UTC, Avimitin commented
I've verified the `v0.0.0-20211216021012-1d35b9e2eb4e` version of the `sys` package can be compiled on RISC-V platform. So no need to upgrade the `go.mod` file. We will patch the old version ourselves.

And I am still trying to verify the minimal required version.

2022-11-30 15:44 UTC, debarshiray commented
> I've verified the `v0.0.0-20211216021012-1d35b9e2eb4e` version of the `sys` package can be compiled on RISC-V platform. So no need to upgrade the `go.mod` file. We will patch the old version ourselves.
> 
> And I am still trying to verify the minimal required version.

Fantastic!

Do you think we also [need](https://tip.golang.org/doc/go1.14#riscv) to bump our required Go version to 1.14 in src/go.mod from the current 1.13?

2022-12-02 00:55 UTC, Avimitin commented
> > I've verified the `v0.0.0-20211216021012-1d35b9e2eb4e` version of the `sys` package can be compiled on RISC-V platform. So no need to upgrade the `go.mod` file. We will patch the old version ourselves.
> > And I am still trying to verify the minimal required version.
> 
> Fantastic!
> 
> Do you think we also [need](https://tip.golang.org/doc/go1.14#riscv) to bump our required Go version to 1.14 in src/go.mod from the current 1.13?

Yes, this is required. Should I push the change in this PR?

2023-06-13 14:42 UTC, debarshiray commented
Merged through https://github.com/containers/toolbox/pull/1316

Closing this one.

2023-06-13 14:42 UTC, closed without merging

2023-06-13 14:42 UTC, debarshiray commented
Thanks for working on this, @Avimitin !