Improve the error message when running nested inside a non-Toolbx container
containers/toolbox pull request #1295
Opened 2023-05-04 10:11 UTC by nievesmontero

2023-07-13 22:03 UTC, debarshiray requested changes
Is this a continuation of https://github.com/containers/toolbox/pull/1191 ?  It would have been better to continue using the old pull request to keep all the discussion in one place.

Anyway, the tests are failing, and the branch has conflicts.  Did you check the test logs to understand why they are failing?  The tests really need to pass.

2023-07-14 13:26 UTC, nievesmontero commented
> Is this a continuation of #1191 ? It would have been better to continue using the old pull request to keep all the discussion in one place.
> 
> Anyway, the tests are failing, and the branch has conflicts. Did you check the test logs to understand why they are failing? The tests really need to pass.

I paused this PR and moved to https://github.com/containers/toolbox/pull/1301#pullrequestreview-1529297172 to first fix the tests. I expect this PR to be fixed once https://github.com/containers/toolbox/pull/1301#pullrequestreview-1529297172 is fixed.

2023-09-27 20:50 UTC, debarshiray commented
> > Is this a continuation of #1191 ? It would have been better to continue using the old pull request to keep all the discussion in one place.
> > Anyway, the tests are failing, and the branch has conflicts. Did you check the test logs to understand why they are failing? The tests really need to pass.
> 
> I paused this PR and moved to #1301 to first fix the tests. I expect this PR to be fixed once #1301 is fixed.

Did the tests get fixed for this pull request?  Last time they were failing and they haven't been run lately.

It also looks like this branch conflicts with `main`.  Could you please `git rebase ...` it?

2023-09-27 20:51 UTC, debarshiray commented
recheck

2023-09-27 20:56 UTC, debarshiray commented
> > > Is this a continuation of #1191 ? It would have been better to continue using the old pull request to keep all the discussion in one place.
> > > Anyway, the tests are failing, and the branch has conflicts. Did you check the test logs to understand why they are failing? The tests really need to pass.
> > 
> > 
> > I paused this PR and moved to #1301 to first fix the tests. I expect this PR to be fixed once #1301 is fixed.
> 
> Did the tests get fixed for this pull request? Last time they were failing and they haven't been run lately.
> 
> It also looks like this branch conflicts with `main`. Could you please `git rebase ...` it?

Ping

2023-11-01 17:05 UTC, HarryMichal requested changes
You seem to have left the check commented out.

Before this goes in having a test would be nice. Some along the lines of running `podman run -it <some-available-image-in-the-test-suit> toolbox`? Do we need the test to be done per command? Probably not.

2023-11-02 11:46 UTC, nievesmontero commented on src/cmd/root.go
> +
It is not, however, I was testing this because if I remove the comment, all the tests fail on the CI.

2023-11-15 11:27 UTC, nievesmontero commented
recheck

2023-11-15 12:19 UTC, nievesmontero commented on src/cmd/root.go
> +
Any idea on how to face this problem @HarryMichal ?

2023-12-07 23:39 UTC, debarshiray commented
Ping.  What's the status of this pull request?

2023-12-07 23:40 UTC, debarshiray reviewed
Ping. What's the status of this pull request?

2023-12-11 11:09 UTC, nievesmontero commented
> Ping. What's the status of this pull request?

I put it aside while working on the other PRs. I am stucked because of the problem mentioned here https://github.com/containers/toolbox/pull/1295#discussion_r1380165358 by @HarryMichal 
The changes I made to add the error make the tests fail on the CI.

2026-09-16 14:06 UTC, closed without merging